models/Comment.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property int $id
 * @property string|null $text
 * @property int|null $user_id
 * @property int|null $tour_id
 * @property int|null $status
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    const STATUS_ALLOW = 1;
    const STATUS_DISALLOW = 0;

    public static function tableName()
    {
        return 'comment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'tour_id', 'status'], 'integer'],
            [['text'], 'string', 'max' => 255],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tour::className(), 'targetAttribute' => ['tour_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'text' => 'Text',
            'user_id' => 'User ID',
            'tour_id' => 'Tour ID',
            'status' => 'Status',
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'article_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getDate()
    {
        return Yii::$app->formatter->asDate($this->date);
    }
    
    public function isAllowed()
    {
        return $this->status;
    }

    public function allow()
    {
        $this->status = self::STATUS_ALLOW;
        return $this->save(false);
    }

    public function disallow()
    {
        $this->status = self::STATUS_DISALLOW;
        return $this->save(false);
    }
}

views/partials/comment.php
            <?php if(!empty($comments)):?>
            <?php foreach($comments as $comment):?>
            <div class="bottom-comment">
               <!--bottom comment-->
               <div class="comment-img">
                  <img width="50" class="img-circle" src="<?= $comment->user->image; ?>" alt="">
               </div>
               <div class="comment-text">
                  <a href="#" class="replay btn pull-right"> Replay</a>
                  <h5><?= $comment->user->name;?></h5>
                  <p class="comment-date">
                     <?= $comment->getDate();?>
                  </p>
                  <p class="para"><?= $comment->text; ?></p>
               </div>
            </div>
            <?php endforeach;?>
            <?php endif;?>
            <!-- end bottom comment-->
            <?php if(!Yii::$app->user->isGuest):?>
            <div class="leave-comment">
               <!--leave comment-->
               <h4>Leave a reply</h4>
               <?php if(Yii::$app->session->getFlash('comment')):?>
               <div class="alert alert-success" role="alert">
                  <?= Yii::$app->session->getFlash('comment'); ?>
               </div>
               <?php endif;?>
               <?php $form = \yii\widgets\ActiveForm::begin([
                  'action'=>['site/comment', 'id'=>$tour->id],
                  'options'=>['class'=>'form-horizontal contact-form', 'role'=>'form']])?>
               <div class="form-group">
                  <div class="col-md-12">
                     <?= $form->field($commentForm, 'comment')->textarea(['class'=>'form-control','placeholder'=>'Write Message'])->label(false)?>
                  </div>
               </div>
               <button type="submit" class="btn send-btn">Post Comment</button>
               <?php \yii\widgets\ActiveForm::end();?>
            </div>
            <!--end leave comment-->
            <?php endif;?>
         </div>

views/partials/sidebar.php
<?php
use yii\helpers\Url;
?>
<div class="col-md-4" data-sticky_column>
    <div class="primary-sidebar">

        
        <aside class="widget pos-padding">
            <h3 class="widget-title text-uppercase text-center">Последние посты</h3>
            <?php foreach($recent as $tour):?>
                <div class="thumb-latest-posts">
                    <div class="media">
                        <div class="media-left">
                            <a href="<?= Url::toRoute(['site/singletour','id'=>$tour->id]);?>" class="popular-img"><img src="<?= $tour->getImage();?>" alt="">
                                <div class="p-overlay"></div>
                            </a>
                        </div>
                        <div class="p-content">
                            <a href="<?= Url::toRoute(['site/singletour','id'=>$tour->id]);?>" class="text-uppercase"><?= $tour->title?></a>
                            <span class="p-date"><?= $tour->getDate();?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </aside>
        <aside class="widget border pos-padding">
            <h3 class="widget-title text-uppercase text-center">Категории</h3>
            <ul>
                <?php foreach($categories as $category):?>
                    <li>
                        <a href="<?= Url::toRoute(['site/category','id'=>$category->id]);?>"><?= $category->title?></a>
                        <span class="post-count pull-right"> (<?= $category->getTourCount();?>)</span>
                    </li>
                <?php endforeach;?>

            </ul>
        </aside>
    </div>
</div>